// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMtefqSpn_pK5LiZAuTFVif0e0PX6oanI',
    appId: '1:286463022361:web:7f70fee07669d2205b2188',
    messagingSenderId: '286463022361',
    projectId: 'ceygo-4e4d4',
    authDomain: 'ceygo-4e4d4.firebaseapp.com',
    storageBucket: 'ceygo-4e4d4.appspot.com',
    measurementId: 'G-JN74JJ6GQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-u3pLZzLzh8J3NS5eeQk37ETFcIhUtRk',
    appId: '1:286463022361:android:347490ff6c7565635b2188',
    messagingSenderId: '286463022361',
    projectId: 'ceygo-4e4d4',
    storageBucket: 'ceygo-4e4d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu-8bfeHkLvQDuwOgP2wW78xPPKhjuhx4',
    appId: '1:286463022361:ios:6b491d52e0212df55b2188',
    messagingSenderId: '286463022361',
    projectId: 'ceygo-4e4d4',
    storageBucket: 'ceygo-4e4d4.appspot.com',
    iosClientId: '286463022361-ajuljtjs2f5a0vr2cineol370eovhhjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ceyGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu-8bfeHkLvQDuwOgP2wW78xPPKhjuhx4',
    appId: '1:286463022361:ios:6b491d52e0212df55b2188',
    messagingSenderId: '286463022361',
    projectId: 'ceygo-4e4d4',
    storageBucket: 'ceygo-4e4d4.appspot.com',
    iosClientId: '286463022361-ajuljtjs2f5a0vr2cineol370eovhhjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ceyGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMtefqSpn_pK5LiZAuTFVif0e0PX6oanI',
    appId: '1:286463022361:web:8e935c67b04a73a45b2188',
    messagingSenderId: '286463022361',
    projectId: 'ceygo-4e4d4',
    authDomain: 'ceygo-4e4d4.firebaseapp.com',
    storageBucket: 'ceygo-4e4d4.appspot.com',
    measurementId: 'G-YNJ9MC4R8P',
  );
}
